Script cleanup

diff --git a/packaging/sun-pkg/server/build_server_pkg b/packaging/sun-pkg/server/build_server_pkg
--- a/packaging/sun-pkg/server/build_server_pkg
+++ b/packaging/sun-pkg/server/build_server_pkg
@@ -1,22 +1,31 @@
 #!/bin/sh -x
+
 CFLAGS="-g -O2";export CFLAGS
 LD_LIBRARY_PATH=/opt/csw/lib:/usr/lib;export LD_LIBRARY_PATH
 PATH=/usr/sfw/bin:/opt/csw/gcc3/bin:/usr/ccs/bin:/usr/bin:/usr/sbin:/opt/csw/bin;export PATH
 PKG_CONFIG_PATH=/opt/csw/lib/pkgconfig;export PKG_CONFIG_PATH
 BUILD_DIR=/home/paddy/amanda-build; export BUILD_DIR
+#BUILD_DIR=`pwd`/solaris_build; export BUILD_DIR
+
 MAJOR_VERSION=2.6
 MINOR_VERSION=1
 VERSION=$MAJOR_VERSION.$MINOR_VERSION
 
+#Location of finished package
+FINAL_PKG_DEST=/home/amanda/rpms/amanda/SOLARIS_10_x86/ace/latest/latest/server
+#FINAL_PKG_DEST=`pwd`
+
+#Log file from make and configure
+log=`pwd`/buildlog.txt
+
 SBIN_DIR=/opt/amanda/sbin
 BIN_DIR=/opt/amanda/bin
 SYSCONF_DIR=/etc/opt
-LIB_DIR=/opt/amanda/lib
-LIBEXEC_DIR=/opt/amanda/lib
+LIB_DIR=${PREFIX}/lib
+LIBEXEC_DIR=${PREFIX}/lib
 LOCALSTATE_DIR=/var
 AMANDA_DIR=/var/opt/amanda
-MANDIR=/opt/amanda/man
-PREFIX=/opt/amanda
+MANDIR=${PREFIX}/man
 
 source_tar_location=/home/amanda/rpms/amanda/TARBALL/ace/$MAJOR_VERSION/$MINOR_VERSION/make_dist
 latest_tarball=`ls -1tr $source_tar_location|tail -1`
@@ -26,7 +35,7 @@ cd $BUILD_DIR;
 rm -rf $amanda_source_name
 cp $source_tar_location/$latest_tarball .
 echo "latest tarball is : $source_tar_location/$latest_tarball"
-gtar xvfz $latest_tarball
+gtar xfz $latest_tarball
 
 config_options="--with-user=amandabackup \
                 --with-group=disk \
@@ -80,11 +89,15 @@ echo "Building amanda..."
     make clean >> $log 2>&1
     echo "make " | tee -a $log
     make  >> $log 2>&1
-    rm -rf $BUILD_DIR/build  
+    [ $? -ne 0 ] && echo "Failed to make Amanda" && exit 1
+
+    # Now that we've built the software, install into a fake root.
+    [ -d $BUILD_DIR ] && rm -rf $BUILD_DIR/build  
     make DESTDIR=$BUILD_DIR/build install  >> $log 2>&1
     rc=$?
     if [ $rc -ne 0 ]; then
         echo "make failed:  Check" $log "for errors" 1>&2 
+        exit 1
     fi
 
     cd $BUILD_DIR/build
@@ -93,6 +106,7 @@ echo "Building amanda..."
     echo "i preinstall=./preinstall" >> pkgproto
     echo "i postinstall=./postinstall" >> pkgproto
     echo "i copyright=./copyright" >> pkgproto
+    mkdir -p var/opt/amanda
     echo "Amanda Community Edition - version $VERSION" > var/opt/amanda/amanda-release
     chown amandabackup:disk $BUILD_DIR/build/var/opt/amanda
     pkgproto opt var >> pkgproto 
@@ -102,6 +116,6 @@ echo "Building amanda..."
     pkgtrans -s `pwd` AmandaBackupServer-$VERSION-Sun-10-intel.pkg<<EOF
 
 EOF
-cp AmandaBackupServer-$VERSION-Sun-10-intel.pkg /home/amanda/rpms/amanda/SOLARIS_10_x86/ace/latest/latest/server
+cp AmandaBackupServer-$VERSION-Sun-10-intel.pkg ${FINAL_PKG_DEST} 
 )
 exit $rc
